version: "3.8"

services:
  git-nostr-bridge:
    image: git-nostr-bridge
    build:
      context: ./gitnostr
      dockerfile: Dockerfile
    ports: [
      22:22
    ]
    volumes:
      - ./gitnostr/:/home/git-nostr
    container_name: git-nostr-bridge
  nostrgit:
    image: nostrgit
    build:
      context: .
      dockerfile: Dockerfile
    ports: [
      3000:3000
    ]
    volumes:
      - ./:/usr/src/nostrgit
    tty: true
    container_name: nostrgit